import type {
  Attachment,
  Message,
  Profile,
  Ticket,
  TicketEvent,
} from "@pearl27/contracts";

// Provisional typed client (§3). The OpenAPI spec generated by apps/api is
// authoritative once it exists; until then this hand-written surface lets
// generation and MSW mocks work from day one.

export interface Page<T> {
  items: T[];
  nextCursor: string | null;
}

export interface ApiClientOptions {
  baseUrl: string;
  fetchFn?: typeof fetch;
}

function req(baseUrl: string, fetchFn: typeof fetch) {
  return async <T>(path: string, init: RequestInit = {}): Promise<T> => {
    const res = await fetchFn(`${baseUrl}${path}`, {
      ...init,
      credentials: "include",
      headers: { "Content-Type": "application/json", ...(init.headers ?? {}) },
    });
    if (!res.ok) {
      const body = await res.json().catch(() => null);
      throw Object.assign(new Error(body?.error?.message ?? `HTTP ${res.status}`), {
        status: res.status,
        code: body?.error?.code ?? `HTTP_${res.status}`,
        fieldErrors: body?.error?.fieldErrors,
      });
    }
    if (res.status === 204) return undefined as T;
    return (await res.json()) as T;
  };
}

export function createApiClient({ baseUrl, fetchFn = fetch }: ApiClientOptions) {
  const call = req(baseUrl, fetchFn);
  return {
    me: () => call<Profile>("/auth/me"),
    logout: () => call<void>("/auth/logout", { method: "POST" }),
    categories: () => call("/categories"),
    knownIssues: () => call("/known-issues"),
    createTicket: (body: unknown) =>
      call<Ticket>("/tickets", { method: "POST", body: JSON.stringify(body) }),
    myTickets: (cursor?: string, limit = 20) =>
      call<Page<Ticket> & { counts: Record<string, number> }>(
        `/tickets/mine?limit=${limit}${cursor ? `&cursor=${cursor}` : ""}`,
      ),
    ticketByReference: (reference: string) => call<Ticket>(`/tickets/${reference}`),
    deskDashboard: () => call("/desk/dashboard"),
    deskTickets: (query = "") => call<Page<Ticket>>(`/desk/tickets${query}`),
    deskTicket: (id: string) =>
      call<Ticket & { events: TicketEvent[]; messages: Message[]; attachments: Attachment[] }>(
        `/desk/tickets/${id}`,
      ),
    claim: (id: string) => call<Ticket>(`/desk/tickets/${id}/claim`, { method: "POST" }),
    release: (id: string, reason?: string) =>
      call<Ticket>(`/desk/tickets/${id}/release`, {
        method: "POST",
        body: JSON.stringify({ reason }),
      }),
    send: (id: string, body: unknown) =>
      call(`/desk/tickets/${id}/send`, { method: "POST", body: JSON.stringify(body) }),
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
