/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteRouteImport } from './routes/desk.route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TicketsRouteRouteImport } from './routes/tickets.route'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$splat'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthDeniedRouteImport } from './routes/auth.denied'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskAdminRouteRouteImport } from './routes/desk.admin.route'
import { Route as DeskQueueRouteImport } from './routes/desk.queue'
import { Route as MyTicketsIndexRouteImport } from './routes/my-tickets.index'
import { Route as MyTicketsSplatRouteImport } from './routes/my-tickets.$splat'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsReferenceRouteImport } from './routes/tickets.$reference'
import { Route as TicketsNewRouteImport } from './routes/tickets.new'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackReferenceRouteImport } from './routes/track.$reference'
import { Route as AdminTicketsIdRouteImport } from './routes/admin.tickets.$id'
import { Route as DeskAdminIndexRouteImport } from './routes/desk.admin.index'
import { Route as DeskAdminAdminsRouteImport } from './routes/desk.admin.admins'
import { Route as DeskAdminAgentsRouteImport } from './routes/desk.admin.agents'
import { Route as DeskAdminAuditRouteImport } from './routes/desk.admin.audit'
import { Route as DeskAdminKnownIssuesRouteImport } from './routes/desk.admin.known-issues'
import { Route as DeskAdminSettingsRouteImport } from './routes/desk.admin.settings'
import { Route as DeskTicketsIdRouteImport } from './routes/desk.tickets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRouteRoute = DeskRouteRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRouteRoute = TicketsRouteRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$splat',
  path: '/admin/$splat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeniedRoute = AuthDeniedRouteImport.update({
  id: '/auth/denied',
  path: '/auth/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskAdminRouteRoute = DeskAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskQueueRoute = DeskQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DeskRouteRoute,
} as any)
const MyTicketsIndexRoute = MyTicketsIndexRouteImport.update({
  id: '/my-tickets/',
  path: '/my-tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsSplatRoute = MyTicketsSplatRouteImport.update({
  id: '/my-tickets/$splat',
  path: '/my-tickets/$splat',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsRouteRoute,
} as any)
const TicketsReferenceRoute = TicketsReferenceRouteImport.update({
  id: '/$reference',
  path: '/$reference',
  getParentRoute: () => TicketsRouteRoute,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TicketsRouteRoute,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackReferenceRoute = TrackReferenceRouteImport.update({
  id: '/track/$reference',
  path: '/track/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsIdRoute = AdminTicketsIdRouteImport.update({
  id: '/admin/tickets/$id',
  path: '/admin/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAdminIndexRoute = DeskAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskAdminRouteRoute,
} as any)
const DeskAdminAdminsRoute = DeskAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => DeskAdminRouteRoute,
} as any)
const DeskAdminAgentsRoute = DeskAdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DeskAdminRouteRoute,
} as any)
const DeskAdminAuditRoute = DeskAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DeskAdminRouteRoute,
} as any)
const DeskAdminKnownIssuesRoute = DeskAdminKnownIssuesRouteImport.update({
  id: '/known-issues',
  path: '/known-issues',
  getParentRoute: () => DeskAdminRouteRoute,
} as any)
const DeskAdminSettingsRoute = DeskAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskAdminRouteRoute,
} as any)
const DeskTicketsIdRoute = DeskTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => DeskRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/tickets': typeof TicketsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/desk/admin': typeof DeskAdminRouteRouteWithChildren
  '/admin/$splat': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/desk/queue': typeof DeskQueueRoute
  '/my-tickets/$splat': typeof MyTicketsSplatRoute
  '/tickets/$reference': typeof TicketsReferenceRoute
  '/tickets/new': typeof TicketsNewRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/desk/admin/admins': typeof DeskAdminAdminsRoute
  '/desk/admin/agents': typeof DeskAdminAgentsRoute
  '/desk/admin/audit': typeof DeskAdminAuditRoute
  '/desk/admin/known-issues': typeof DeskAdminKnownIssuesRoute
  '/desk/admin/settings': typeof DeskAdminSettingsRoute
  '/desk/tickets/$id': typeof DeskTicketsIdRoute
  '/desk/admin/': typeof DeskAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/admin/$splat': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/desk/queue': typeof DeskQueueRoute
  '/my-tickets/$splat': typeof MyTicketsSplatRoute
  '/tickets/$reference': typeof TicketsReferenceRoute
  '/tickets/new': typeof TicketsNewRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/admin': typeof AdminIndexRoute
  '/desk': typeof DeskIndexRoute
  '/my-tickets': typeof MyTicketsIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/track': typeof TrackIndexRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/desk/admin/admins': typeof DeskAdminAdminsRoute
  '/desk/admin/agents': typeof DeskAdminAgentsRoute
  '/desk/admin/audit': typeof DeskAdminAuditRoute
  '/desk/admin/known-issues': typeof DeskAdminKnownIssuesRoute
  '/desk/admin/settings': typeof DeskAdminSettingsRoute
  '/desk/tickets/$id': typeof DeskTicketsIdRoute
  '/desk/admin': typeof DeskAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/tickets': typeof TicketsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/desk/admin': typeof DeskAdminRouteRouteWithChildren
  '/admin/$splat': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/desk/queue': typeof DeskQueueRoute
  '/my-tickets/$splat': typeof MyTicketsSplatRoute
  '/tickets/$reference': typeof TicketsReferenceRoute
  '/tickets/new': typeof TicketsNewRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/desk/admin/admins': typeof DeskAdminAdminsRoute
  '/desk/admin/agents': typeof DeskAdminAgentsRoute
  '/desk/admin/audit': typeof DeskAdminAuditRoute
  '/desk/admin/known-issues': typeof DeskAdminKnownIssuesRoute
  '/desk/admin/settings': typeof DeskAdminSettingsRoute
  '/desk/tickets/$id': typeof DeskTicketsIdRoute
  '/desk/admin/': typeof DeskAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/tickets'
    | '/sign-in'
    | '/desk/admin'
    | '/admin/$splat'
    | '/admin/login'
    | '/auth/denied'
    | '/desk/queue'
    | '/my-tickets/$splat'
    | '/tickets/$reference'
    | '/tickets/new'
    | '/track/$reference'
    | '/admin/'
    | '/desk/'
    | '/my-tickets/'
    | '/tickets/'
    | '/track/'
    | '/admin/tickets/$id'
    | '/desk/admin/admins'
    | '/desk/admin/agents'
    | '/desk/admin/audit'
    | '/desk/admin/known-issues'
    | '/desk/admin/settings'
    | '/desk/tickets/$id'
    | '/desk/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/admin/$splat'
    | '/admin/login'
    | '/auth/denied'
    | '/desk/queue'
    | '/my-tickets/$splat'
    | '/tickets/$reference'
    | '/tickets/new'
    | '/track/$reference'
    | '/admin'
    | '/desk'
    | '/my-tickets'
    | '/tickets'
    | '/track'
    | '/admin/tickets/$id'
    | '/desk/admin/admins'
    | '/desk/admin/agents'
    | '/desk/admin/audit'
    | '/desk/admin/known-issues'
    | '/desk/admin/settings'
    | '/desk/tickets/$id'
    | '/desk/admin'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/tickets'
    | '/sign-in'
    | '/desk/admin'
    | '/admin/$splat'
    | '/admin/login'
    | '/auth/denied'
    | '/desk/queue'
    | '/my-tickets/$splat'
    | '/tickets/$reference'
    | '/tickets/new'
    | '/track/$reference'
    | '/admin/'
    | '/desk/'
    | '/my-tickets/'
    | '/tickets/'
    | '/track/'
    | '/admin/tickets/$id'
    | '/desk/admin/admins'
    | '/desk/admin/agents'
    | '/desk/admin/audit'
    | '/desk/admin/known-issues'
    | '/desk/admin/settings'
    | '/desk/tickets/$id'
    | '/desk/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRouteRoute: typeof DeskRouteRouteWithChildren
  TicketsRouteRoute: typeof TicketsRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthDeniedRoute: typeof AuthDeniedRoute
  MyTicketsSplatRoute: typeof MyTicketsSplatRoute
  TrackReferenceRoute: typeof TrackReferenceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MyTicketsIndexRoute: typeof MyTicketsIndexRoute
  TrackIndexRoute: typeof TrackIndexRoute
  AdminTicketsIdRoute: typeof AdminTicketsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$splat': {
      id: '/admin/$splat'
      path: '/admin/$splat'
      fullPath: '/admin/$splat'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/denied': {
      id: '/auth/denied'
      path: '/auth/denied'
      fullPath: '/auth/denied'
      preLoaderRoute: typeof AuthDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/admin': {
      id: '/desk/admin'
      path: '/admin'
      fullPath: '/desk/admin'
      preLoaderRoute: typeof DeskAdminRouteRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/queue': {
      id: '/desk/queue'
      path: '/queue'
      fullPath: '/desk/queue'
      preLoaderRoute: typeof DeskQueueRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/my-tickets/': {
      id: '/my-tickets/'
      path: '/my-tickets'
      fullPath: '/my-tickets/'
      preLoaderRoute: typeof MyTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets/$splat': {
      id: '/my-tickets/$splat'
      path: '/my-tickets/$splat'
      fullPath: '/my-tickets/$splat'
      preLoaderRoute: typeof MyTicketsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof TicketsRouteRoute
    }
    '/tickets/$reference': {
      id: '/tickets/$reference'
      path: '/$reference'
      fullPath: '/tickets/$reference'
      preLoaderRoute: typeof TicketsReferenceRouteImport
      parentRoute: typeof TicketsRouteRoute
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof TicketsRouteRoute
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$reference': {
      id: '/track/$reference'
      path: '/track/$reference'
      fullPath: '/track/$reference'
      preLoaderRoute: typeof TrackReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/$id': {
      id: '/admin/tickets/$id'
      path: '/admin/tickets/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AdminTicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/admin/': {
      id: '/desk/admin/'
      path: '/'
      fullPath: '/desk/admin/'
      preLoaderRoute: typeof DeskAdminIndexRouteImport
      parentRoute: typeof DeskAdminRouteRoute
    }
    '/desk/admin/admins': {
      id: '/desk/admin/admins'
      path: '/admins'
      fullPath: '/desk/admin/admins'
      preLoaderRoute: typeof DeskAdminAdminsRouteImport
      parentRoute: typeof DeskAdminRouteRoute
    }
    '/desk/admin/agents': {
      id: '/desk/admin/agents'
      path: '/agents'
      fullPath: '/desk/admin/agents'
      preLoaderRoute: typeof DeskAdminAgentsRouteImport
      parentRoute: typeof DeskAdminRouteRoute
    }
    '/desk/admin/audit': {
      id: '/desk/admin/audit'
      path: '/audit'
      fullPath: '/desk/admin/audit'
      preLoaderRoute: typeof DeskAdminAuditRouteImport
      parentRoute: typeof DeskAdminRouteRoute
    }
    '/desk/admin/known-issues': {
      id: '/desk/admin/known-issues'
      path: '/known-issues'
      fullPath: '/desk/admin/known-issues'
      preLoaderRoute: typeof DeskAdminKnownIssuesRouteImport
      parentRoute: typeof DeskAdminRouteRoute
    }
    '/desk/admin/settings': {
      id: '/desk/admin/settings'
      path: '/settings'
      fullPath: '/desk/admin/settings'
      preLoaderRoute: typeof DeskAdminSettingsRouteImport
      parentRoute: typeof DeskAdminRouteRoute
    }
    '/desk/tickets/$id': {
      id: '/desk/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/desk/tickets/$id'
      preLoaderRoute: typeof DeskTicketsIdRouteImport
      parentRoute: typeof DeskRouteRoute
    }
  }
}

interface DeskAdminRouteRouteChildren {
  DeskAdminAdminsRoute: typeof DeskAdminAdminsRoute
  DeskAdminAgentsRoute: typeof DeskAdminAgentsRoute
  DeskAdminAuditRoute: typeof DeskAdminAuditRoute
  DeskAdminKnownIssuesRoute: typeof DeskAdminKnownIssuesRoute
  DeskAdminSettingsRoute: typeof DeskAdminSettingsRoute
  DeskAdminIndexRoute: typeof DeskAdminIndexRoute
}

const DeskAdminRouteRouteChildren: DeskAdminRouteRouteChildren = {
  DeskAdminAdminsRoute: DeskAdminAdminsRoute,
  DeskAdminAgentsRoute: DeskAdminAgentsRoute,
  DeskAdminAuditRoute: DeskAdminAuditRoute,
  DeskAdminKnownIssuesRoute: DeskAdminKnownIssuesRoute,
  DeskAdminSettingsRoute: DeskAdminSettingsRoute,
  DeskAdminIndexRoute: DeskAdminIndexRoute,
}

const DeskAdminRouteRouteWithChildren = DeskAdminRouteRoute._addFileChildren(
  DeskAdminRouteRouteChildren,
)

interface DeskRouteRouteChildren {
  DeskAdminRouteRoute: typeof DeskAdminRouteRouteWithChildren
  DeskQueueRoute: typeof DeskQueueRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskTicketsIdRoute: typeof DeskTicketsIdRoute
}

const DeskRouteRouteChildren: DeskRouteRouteChildren = {
  DeskAdminRouteRoute: DeskAdminRouteRouteWithChildren,
  DeskQueueRoute: DeskQueueRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskTicketsIdRoute: DeskTicketsIdRoute,
}

const DeskRouteRouteWithChildren = DeskRouteRoute._addFileChildren(
  DeskRouteRouteChildren,
)

interface TicketsRouteRouteChildren {
  TicketsReferenceRoute: typeof TicketsReferenceRoute
  TicketsNewRoute: typeof TicketsNewRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

const TicketsRouteRouteChildren: TicketsRouteRouteChildren = {
  TicketsReferenceRoute: TicketsReferenceRoute,
  TicketsNewRoute: TicketsNewRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}

const TicketsRouteRouteWithChildren = TicketsRouteRoute._addFileChildren(
  TicketsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRouteRoute: DeskRouteRouteWithChildren,
  TicketsRouteRoute: TicketsRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthDeniedRoute: AuthDeniedRoute,
  MyTicketsSplatRoute: MyTicketsSplatRoute,
  TrackReferenceRoute: TrackReferenceRoute,
  AdminIndexRoute: AdminIndexRoute,
  MyTicketsIndexRoute: MyTicketsIndexRoute,
  TrackIndexRoute: TrackIndexRoute,
  AdminTicketsIdRoute: AdminTicketsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
